Import('env')
env = env.Clone()
Import('proto')

env.Append(CPPFLAGS = '-D_FILE_OFFSET_BITS=64 -D__FreeBSD__=10 -DFUSE_USE_VERSION=26')

fs = env.Object('fs.cc')
Depends(fs, proto)
fs = env.Library('fs', fs)
Return('fs')
