Import('env')
env = env.Clone()
Import('proto')
Import('rpc_channel')

env.Append(CPPFLAGS = '-D_FILE_OFFSET_BITS=64 -D__FreeBSD__=10 -DFUSE_USE_VERSION=26')

env.Program('fs_server',
            [ 'fs.cc',
              'fs_server.cc' ],
            LIBS = [ proto, rpc_channel, 'protobuf', 'fuse' ])
