Import('env')
env = env.Clone()
Import('proto')
Import('fs')
Import('rpc')
Import('mount')

env.Append(FRAMEWORKS = ['Carbon', 'MobileDevice'])
env.Append(FRAMEWORKPATH = ['/System/Library/PrivateFrameworks'])

afc = env.Library('afc',
                  [ 'afc_listener.cc' ])

mobile_fs_library = env.Library('mobile_fs_service',
            [ 'mobile_fs_service.cc' ],
            LIBS = [ proto ])

env.Program('mobile_fs_util',
            [ 'mobile_fs_util.cc' ],
            LIBS = [ proto, fs, mobile_fs_library, 'fuse', rpc,
                     'protobuf', afc, mount ])
