Import('env')
env = env.Clone()
Import('proto')
Import('fs')
Import('rpc_service')

env.Append(FRAMEWORKS = ['Carbon', 'MobileDevice'])
env.Append(FRAMEWORKPATH = ['/System/Library/PrivateFrameworks'])

mobile_fs_library = env.Library('mobile_fs_service',
            [ 'mobile_fs_service.cc' ],
            LIBS = [ proto ])

env.Program('mobile_fs_util',
            [ 'mobile_fs_util.cc' ],
            LIBS = [ proto, fs, rpc_service, mobile_fs_library, 'fuse',
                     'protobuf' ])
