Import('env')
Import('rpc')
Import('proto')
Import('fs')

loopback_fs_service = env.Library('loopback_fs_service',
                                  [ 'loopback_fs_service.cc' ])

env.Append(CPPFLAGS = '-D_FILE_OFFSET_BITS=64 -D__FreeBSD__=10 -DFUSE_USE_VERSION=26')

env.Program('loopback_fs_util',
            [ 'loopback_fs_util.cc' ],
            LIBS = [ fs, rpc, loopback_fs_service, proto,
                     'protobuf', 'fuse_ino64' ])
